/**
 * Traductions de l'application. Partagé entre le process principal (messages
 * du splash et du scan) et le renderer, pour qu'une seule table fasse foi.
 *
 * Conventions :
 *  - `{nom}` est remplacé par `params.nom` ;
 *  - `singulier|pluriel` choisit la forme selon `params.count`.
 */

export type Lang = 'fr' | 'en'

export const LANGUAGES: Lang[] = ['fr', 'en']

export const LANGUAGE_LABELS: Record<Lang, string> = {
  fr: 'Français',
  en: 'English'
}

const fr = {
  'nav.home': 'Accueil',
  'nav.playlists': 'Playlists',
  'nav.albums': 'Albums',
  'nav.artists': 'Artistes',
  'nav.tempo': 'Tempo',
  'search.placeholder': 'Que voulez-vous écouter ?',

  'action.notifications': 'Notifications',
  'action.profile': 'Profil',
  'action.engine': 'Moteur Audii',
  'action.themeToLight': 'Passer en thème clair',
  'action.themeToDark': 'Passer en thème sombre',

  'window.minimize': 'Réduire',
  'window.maximize': 'Agrandir',
  'window.restore': 'Restaurer',
  'window.close': 'Fermer',

  'sidebar.recent': 'Récents',
  'sidebar.sort': 'Trier',
  'sidebar.addFolder': 'Ajouter un dossier',
  'sidebar.collapse': 'Replier le panneau',
  'sidebar.expand': 'Déplier le panneau',
  'sidebar.playlist': 'Playlist',
  'sidebar.tempoSection': 'Tempo · auto',
  'sidebar.autoGenerated': '{name} — généré automatiquement',
  'sidebar.empty': 'Aucune playlist. Ajoutez un dossier de musique avec « + ».',

  'track.unknownArtist': 'Artiste inconnu',
  'playlist.all': 'Toute la musique',
  'favorites.title': 'Coups de cœur',
  'favorites.subtitle': 'Vos titres aimés',
  'favorites.empty': "Aucun coup de cœur pour l'instant : touchez le ♥ sur un titre pour le retrouver ici.",
  'style.label': 'Style',
  'style.all': 'Tous les styles',
  'style.unknown': 'Non classé',
  'vibe.styleLock': 'Rester dans le style',
  'vibe.styleLockHint':
    "Sans ce garde-fou, l'enchaînement suit le BPM à l'aveugle et peut passer du gospel au drill. Activé, Audii reste dans l'univers du morceau en cours.",
  'vibe.whisper': "Le mot d'Audii",
  'vibe.whisperHint':
    "Une phrase écrite pour le morceau qui ouvre une playlist. Jamais deux fois dans la même demi-heure, jamais sur un simple enchaînement.",

  'whisper.kicker': "Le mot d'Audii",
  'whisper.dismiss': 'Masquer ce message',

  'table.title': 'Titre',
  'table.album': 'Album',
  'table.added': 'Ajouté le',
  'table.time': 'Durée',

  'row.play': 'Lire',
  'row.pause': 'Pause',
  'row.favorite': 'Favori',
  'row.more': "Plus d'options",
  'row.playNow': 'Lire maintenant',
  'row.reveal': "Afficher dans l'explorateur",

  'playlist.subtitle': 'Playlist • {songs} • {duration}',
  'playlist.songs': '{count} morceau|{count} morceaux',
  'playlist.play': 'Lire la playlist',
  'playlist.options': 'Options de la playlist',
  'playlist.pin': 'Épingler',

  'panel.topArtists': 'Top artistes',
  'panel.options': 'Options',
  'panel.empty': 'Votre bibliothèque est vide.',
  'artist.meta': '{tracks} • {albums}',
  'artist.tracks': '{count} titre|{count} titres',
  'artist.albums': '{count} album|{count} albums',
  'artist.listen': 'Double-clic pour écouter {name}',

  'promo.title': 'La musique sans coupure',
  'promo.text': 'Profitez de la musique sans publicité avec le forfait premium.',
  'promo.cta': 'Passer au premium',

  'player.nothing': 'Rien en lecture',
  'player.choose': 'Choisissez un morceau',
  'player.prev': 'Précédent',
  'player.next': 'Suivant',
  'player.play': 'Lire',
  'player.pause': 'Pause',
  'player.shuffle': 'Lecture aléatoire',
  'player.repeat': 'Répétition : {mode}',
  'player.volume': 'Volume',
  'player.smartDim': 'Smart Dim actif',
  'player.favorite': 'Ajouter aux favoris',
  'player.openTrack': 'Ouvrir la page du morceau',
  'player.trackPage': 'Page du morceau en cours',
  'repeat.off': 'désactivée',
  'repeat.all': 'toute la file',
  'repeat.one': 'le morceau',

  'vibe.title': 'Moteur Audii',
  'vibe.subtitle': 'Le bon tempo, au bon moment.',
  'vibe.close': 'Fermer',
  'vibe.sourceTap': 'Imposé par Tap-Tempo',
  'vibe.sourceTag': 'Lu dans les tags du fichier',
  'vibe.sourceAnalyzed': 'Estimé par analyse locale',
  'vibe.analyzing': 'Analyse du morceau en cours…',
  'vibe.noTrack': 'Aucun morceau en lecture',
  'vibe.target': "Cible d'enchaînement :",
  'vibe.lockVibe': 'Lock-Vibe',
  'vibe.lockVibeAria': 'Continuum de rythme',
  'vibe.lockVibeHint':
    'Verrouille la signature rythmique du morceau en cours et enchaîne le suivant sans rupture.',
  'vibe.energy': 'Énergie',
  'vibe.energyAria': "Sélecteur d'énergie",
  'vibe.tapTempo': 'Tap-Tempo',
  'vibe.tapPrompt': 'Tapotez au rythme',
  'vibe.tapHint': 'clic ou touche T — 3 à 4 fois',
  'vibe.reset': 'réinitialiser',
  'vibe.noiseSense': 'Noise Sense',
  'vibe.noiseAria': 'Atténuation intelligente',
  'vibe.noiseHint':
    "Le micro écoute l'environnement : en cas de bruit fort, le volume descend à 20 % puis remonte en fondu.",
  'vibe.sensitivity': 'Sensibilité',
  'vibe.sensitivityAria': 'Sensibilité Noise Sense',
  'vibe.nominal': 'Volume nominal',
  'vibe.smartDim': 'Smart Dim {percent} %',
  'vibe.appearance': 'Apparence',
  'vibe.language': 'Langue',
  'vibe.profile': 'Profil',
  'vibe.change': 'changer',
  'vibe.localProfile': 'Profil local, sans compte en ligne',
  'vibe.library': 'Bibliothèque locale',
  'vibe.trackCount': '{count} titre|{count} titres',
  'vibe.noFolder': 'Aucun dossier suivi',
  'vibe.addFolder': 'Ajouter un dossier',
  'vibe.rescan': 'Rescanner',
  'vibe.removeFolder': 'Retirer',

  'theme.light': 'Clair',
  'theme.dark': 'Sombre',
  'theme.system': 'Système',

  'now.kicker': 'En lecture',
  'now.bpmTag': 'BPM (tag)',
  'now.bpmAnalyzed': 'BPM (analysé)',
  'now.bpm': 'BPM',
  'now.energy': 'énergie',
  'now.duration': 'durée',
  'now.genre': 'genre',
  'now.addFavorite': 'Ajouter aux favoris',
  'now.inFavorites': 'Dans les favoris',
  'now.showFile': 'Voir le fichier',
  'now.emptyTitle': 'Rien en lecture',
  'now.emptyText': 'Choisissez un morceau : sa page affichera le tempo et ce qui peut suivre.',
  'now.emptyCta': 'Ouvrir mes playlists',

  'continue.title': 'Continuer sur ce rythme',
  'continue.target': 'Cible {bpm} BPM — enchaînements les plus fluides depuis {source}.',
  'continue.fromQueue': 'la file en cours',
  'continue.fromLibrary': 'toute la bibliothèque',
  'continue.estimating': "Tempo du morceau en cours d'estimation…",
  'continue.lockOn': 'Lock-Vibe actif',
  'continue.lockOff': 'Activer Lock-Vibe',
  'continue.lockTitle': 'Enchaîner automatiquement sur ce rythme',
  'continue.empty': "Pas encore d'autre titre à enchaîner.",
  'continue.same': 'même tempo',
  'continue.unknown': 'tempo inconnu',
  'continue.pending':
    "{count} titre sans tempo connu — les suggestions s'affinent au fur et à mesure.|{count} titres sans tempo connu — les suggestions s'affinent au fur et à mesure.",
  'continue.analyzeAll': 'Analyser tout',

  'tempo.title': 'Tempo',
  'tempo.sorted': '{count} titre rangé par BPM|{count} titres rangés par BPM',
  'tempo.pending': '{count} en attente d’analyse',
  'tempo.sortAria': 'Sens du tri',
  'tempo.fastToSlow': 'Rapide → lent',
  'tempo.slowToFast': 'Lent → rapide',
  'tempo.analyzeN': 'Analyser {count} titre|Analyser {count} titres',
  'tempo.allTitle': 'Tout, trié par tempo',
  'tempo.allSubDesc': '{tracks} · du plus rapide au plus lent',
  'tempo.allSubAsc': '{tracks} · du plus lent au plus rapide',
  'tempo.tracks': '{count} titre|{count} titres',
  'tempo.cardMeta': '{tracks} · {duration} · moy. {bpm} BPM',
  'tempo.playBand': 'Lire cette tranche',
  'tempo.seeAll': 'Voir les {count} titres',
  'tempo.emptyTitle': "Aucun tempo connu pour l'instant",
  'tempo.emptyText':
    'Audii estime le BPM de chaque fichier en local. Lancez l’analyse pour que les playlists tempo se construisent toutes seules.',
  'tempo.emptyCta': 'Analyser la bibliothèque',

  'grid.albums': 'Albums',
  'grid.artists': 'Artistes',
  'grid.recent': 'Ajoutés récemment',
  'grid.items': '{count} élément|{count} éléments',

  'empty.title': 'Votre musique, ici',
  'empty.text':
    'Audii lit directement les fichiers audio de votre PC — MP3, FLAC, M4A, WAV, OGG, Opus…\nAjoutez un dossier pour construire votre bibliothèque : rien ne quitte votre machine.',
  'empty.cta': 'Choisir un dossier',
  'empty.working': 'Analyse en cours…',

  'scan.title': 'Analyse de la bibliothèque',
  'scan.done': 'Bibliothèque à jour',

  'login.welcome': 'Bienvenue',
  'login.sub': 'Créez votre profil : il reste sur cet ordinateur, sans mot de passe ni connexion Internet.',
  'login.name': 'Nom',
  'login.namePlaceholder': 'Comment on vous appelle ?',
  'login.nameError': 'Au moins deux caractères.',
  'login.email': 'E-mail',
  'login.optional': 'facultatif',
  'login.emailPlaceholder': "pour l'abonnement plus tard",
  'login.emailError': 'Adresse invalide.',
  'login.color': 'Couleur',
  'login.hue': 'Teinte {value}',
  'login.submit': 'Commencer à écouter',
  'login.guest': 'Continuer en invité',
  'login.guestName': 'Invité',
  'login.claim': 'Le bon tempo, au bon moment.',
  'login.point1': 'Vos fichiers, lus depuis votre disque — rien ne part en ligne.',
  'login.point2': 'Lock-Vibe enchaîne les titres sans casser le rythme.',
  'login.point3': 'Noise Sense baisse le son quand on vous parle.',
  'login.credit': 'Propulsé par Buyticle',
  'login.language': 'Langue',

  'error.format': 'Format non supporté par le lecteur',
  'error.playback': 'Lecture impossible',
  'error.mic': 'Micro indisponible : Noise Sense désactivé',
  'error.scan': 'Scan impossible',
  'error.scanRunning': 'Un scan est déjà en cours',

  'splash.init': 'Initialisation…',
  'splash.prefs': 'Chargement des préférences…',
  'splash.library': 'Ouverture de la bibliothèque…',
  'splash.cached': '{count} morceau en cache|{count} morceaux en cache',
  'splash.noFolder': 'Aucun dossier musical configuré',
  'splash.analyzing': 'Analyse de vos fichiers audio…',
  'splash.exploring': 'Exploration… {count} fichier|Exploration… {count} fichiers',
  'splash.reading': 'Lecture des métadonnées {current}/{total}',
  'splash.ready': 'Prêt',
  'splash.degraded': 'Démarrage en mode dégradé',

  'scanner.exploring': 'Exploration des dossiers…',
  'scanner.found': '{count} fichier trouvé|{count} fichiers trouvés',
  'scanner.reading': 'Lecture des métadonnées…',
  'scanner.done': '{count} morceau dans la bibliothèque|{count} morceaux dans la bibliothèque',

  'dialog.addFolder': 'Ajouter un dossier musical'
} satisfies Record<string, string>

export type MessageKey = keyof typeof fr

const en: Record<MessageKey, string> = {
  'nav.home': 'Home',
  'nav.playlists': 'Playlists',
  'nav.albums': 'Albums',
  'nav.artists': 'Artists',
  'nav.tempo': 'Tempo',
  'search.placeholder': 'What do you want to listen?',

  'action.notifications': 'Notifications',
  'action.profile': 'Profile',
  'action.engine': 'Audii engine',
  'action.themeToLight': 'Switch to light theme',
  'action.themeToDark': 'Switch to dark theme',

  'window.minimize': 'Minimize',
  'window.maximize': 'Maximize',
  'window.restore': 'Restore',
  'window.close': 'Close',

  'sidebar.recent': 'Recent',
  'sidebar.sort': 'Sort',
  'sidebar.addFolder': 'Add a folder',
  'sidebar.collapse': 'Collapse panel',
  'sidebar.expand': 'Expand panel',
  'sidebar.playlist': 'Playlist',
  'sidebar.tempoSection': 'Tempo · auto',
  'sidebar.autoGenerated': '{name} — generated automatically',
  'sidebar.empty': 'No playlist yet. Add a music folder with “+”.',

  'track.unknownArtist': 'Unknown artist',
  'playlist.all': 'All music',
  'favorites.title': 'Favourites',
  'favorites.subtitle': 'Tracks you liked',
  'favorites.empty': 'No favourite yet: tap the ♥ on a track to find it here.',
  'style.label': 'Style',
  'style.all': 'All styles',
  'style.unknown': 'Unclassified',
  'vibe.styleLock': 'Stay in style',
  'vibe.styleLockHint':
    'Without this guard the engine follows BPM blindly and can jump from gospel to drill. Turned on, Audii stays in the current track’s world.',
  'vibe.whisper': 'A word from Audii',
  'vibe.whisperHint':
    'One line written for the track that opens a playlist. Never twice in the same half hour, never on a plain track change.',

  'whisper.kicker': 'A word from Audii',
  'whisper.dismiss': 'Hide this message',

  'table.title': 'Title',
  'table.album': 'Album',
  'table.added': 'Added date',
  'table.time': 'Time',

  'row.play': 'Play',
  'row.pause': 'Pause',
  'row.favorite': 'Favourite',
  'row.more': 'More options',
  'row.playNow': 'Play now',
  'row.reveal': 'Show in file explorer',

  'playlist.subtitle': 'Playlist • {songs} • {duration}',
  'playlist.songs': '{count} song|{count} songs',
  'playlist.play': 'Play playlist',
  'playlist.options': 'Playlist options',
  'playlist.pin': 'Pin',

  'panel.topArtists': 'Top Artists',
  'panel.options': 'Options',
  'panel.empty': 'Your library is empty.',
  'artist.meta': '{tracks} • {albums}',
  'artist.tracks': '{count} track|{count} tracks',
  'artist.albums': '{count} album|{count} albums',
  'artist.listen': 'Double-click to play {name}',

  'promo.title': 'Uninterrupted Music Awaits',
  'promo.text': 'Enjoy ad-free music with our premium plan.',
  'promo.cta': 'Upgrade now',

  'player.nothing': 'Nothing playing',
  'player.choose': 'Pick a track',
  'player.prev': 'Previous',
  'player.next': 'Next',
  'player.play': 'Play',
  'player.pause': 'Pause',
  'player.shuffle': 'Shuffle',
  'player.repeat': 'Repeat: {mode}',
  'player.volume': 'Volume',
  'player.smartDim': 'Smart Dim active',
  'player.favorite': 'Add to favourites',
  'player.openTrack': 'Open track page',
  'player.trackPage': 'Current track page',
  'repeat.off': 'off',
  'repeat.all': 'whole queue',
  'repeat.one': 'this track',

  'vibe.title': 'Audii engine',
  'vibe.subtitle': 'The right tempo, at the right moment.',
  'vibe.close': 'Close',
  'vibe.sourceTap': 'Set by Tap-Tempo',
  'vibe.sourceTag': 'Read from the file tags',
  'vibe.sourceAnalyzed': 'Estimated by local analysis',
  'vibe.analyzing': 'Analysing this track…',
  'vibe.noTrack': 'Nothing playing',
  'vibe.target': 'Next-track target:',
  'vibe.lockVibe': 'Lock-Vibe',
  'vibe.lockVibeAria': 'Rhythm continuum',
  'vibe.lockVibeHint': 'Locks the rhythmic signature of the current track and blends the next one seamlessly.',
  'vibe.energy': 'Energy',
  'vibe.energyAria': 'Energy selector',
  'vibe.tapTempo': 'Tap-Tempo',
  'vibe.tapPrompt': 'Tap to the beat',
  'vibe.tapHint': 'click or press T — 3 to 4 times',
  'vibe.reset': 'reset',
  'vibe.noiseSense': 'Noise Sense',
  'vibe.noiseAria': 'Smart attenuation',
  'vibe.noiseHint':
    'The mic listens to the room: on a loud noise the volume drops to 20% and fades back in afterwards.',
  'vibe.sensitivity': 'Sensitivity',
  'vibe.sensitivityAria': 'Noise Sense sensitivity',
  'vibe.nominal': 'Full volume',
  'vibe.smartDim': 'Smart Dim {percent}%',
  'vibe.appearance': 'Appearance',
  'vibe.language': 'Language',
  'vibe.profile': 'Profile',
  'vibe.change': 'change',
  'vibe.localProfile': 'Local profile, no online account',
  'vibe.library': 'Local library',
  'vibe.trackCount': '{count} track|{count} tracks',
  'vibe.noFolder': 'No folder watched',
  'vibe.addFolder': 'Add a folder',
  'vibe.rescan': 'Rescan',
  'vibe.removeFolder': 'Remove',

  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.system': 'System',

  'now.kicker': 'Now playing',
  'now.bpmTag': 'BPM (tag)',
  'now.bpmAnalyzed': 'BPM (analysed)',
  'now.bpm': 'BPM',
  'now.energy': 'energy',
  'now.duration': 'length',
  'now.genre': 'genre',
  'now.addFavorite': 'Add to favourites',
  'now.inFavorites': 'In favourites',
  'now.showFile': 'Show the file',
  'now.emptyTitle': 'Nothing playing',
  'now.emptyText': 'Pick a track: its page shows the tempo and what can follow.',
  'now.emptyCta': 'Open my playlists',

  'continue.title': 'Keep this rhythm going',
  'continue.target': 'Target {bpm} BPM — smoothest transitions from {source}.',
  'continue.fromQueue': 'the current queue',
  'continue.fromLibrary': 'the whole library',
  'continue.estimating': 'Estimating this track’s tempo…',
  'continue.lockOn': 'Lock-Vibe on',
  'continue.lockOff': 'Turn on Lock-Vibe',
  'continue.lockTitle': 'Automatically keep this rhythm',
  'continue.empty': 'No other track to blend into yet.',
  'continue.same': 'same tempo',
  'continue.unknown': 'unknown tempo',
  'continue.pending':
    '{count} track has no tempo yet — suggestions sharpen as analysis runs.|{count} tracks have no tempo yet — suggestions sharpen as analysis runs.',
  'continue.analyzeAll': 'Analyse all',

  'tempo.title': 'Tempo',
  'tempo.sorted': '{count} track sorted by BPM|{count} tracks sorted by BPM',
  'tempo.pending': '{count} awaiting analysis',
  'tempo.sortAria': 'Sort direction',
  'tempo.fastToSlow': 'Fast → slow',
  'tempo.slowToFast': 'Slow → fast',
  'tempo.analyzeN': 'Analyse {count} track|Analyse {count} tracks',
  'tempo.allTitle': 'Everything, sorted by tempo',
  'tempo.allSubDesc': '{tracks} · fastest to slowest',
  'tempo.allSubAsc': '{tracks} · slowest to fastest',
  'tempo.tracks': '{count} track|{count} tracks',
  'tempo.cardMeta': '{tracks} · {duration} · avg. {bpm} BPM',
  'tempo.playBand': 'Play this band',
  'tempo.seeAll': 'See all {count} tracks',
  'tempo.emptyTitle': 'No tempo known yet',
  'tempo.emptyText':
    'Audii estimates the BPM of every file locally. Run the analysis and the tempo playlists build themselves.',
  'tempo.emptyCta': 'Analyse the library',

  'grid.albums': 'Albums',
  'grid.artists': 'Artists',
  'grid.recent': 'Recently added',
  'grid.items': '{count} item|{count} items',

  'empty.title': 'Your music, right here',
  'empty.text':
    'Audii plays the audio files already on your PC — MP3, FLAC, M4A, WAV, OGG, Opus…\nAdd a folder to build your library: nothing ever leaves your machine.',
  'empty.cta': 'Choose a folder',
  'empty.working': 'Scanning…',

  'scan.title': 'Scanning the library',
  'scan.done': 'Library up to date',

  'login.welcome': 'Welcome',
  'login.sub': 'Create your profile: it stays on this computer, no password and no internet connection.',
  'login.name': 'Name',
  'login.namePlaceholder': 'What should we call you?',
  'login.nameError': 'At least two characters.',
  'login.email': 'E-mail',
  'login.optional': 'optional',
  'login.emailPlaceholder': 'for the subscription later on',
  'login.emailError': 'Invalid address.',
  'login.color': 'Colour',
  'login.hue': 'Hue {value}',
  'login.submit': 'Start listening',
  'login.guest': 'Continue as guest',
  'login.guestName': 'Guest',
  'login.claim': 'The right tempo, at the right moment.',
  'login.point1': 'Your files, read from your own disk — nothing goes online.',
  'login.point2': 'Lock-Vibe blends tracks without breaking the rhythm.',
  'login.point3': 'Noise Sense turns the volume down when someone talks to you.',
  'login.credit': 'Powered by Buyticle',
  'login.language': 'Language',

  'error.format': 'Format not supported by the player',
  'error.playback': 'Playback failed',
  'error.mic': 'Microphone unavailable: Noise Sense turned off',
  'error.scan': 'Scan failed',
  'error.scanRunning': 'A scan is already running',

  'splash.init': 'Starting up…',
  'splash.prefs': 'Loading preferences…',
  'splash.library': 'Opening the library…',
  'splash.cached': '{count} track cached|{count} tracks cached',
  'splash.noFolder': 'No music folder configured',
  'splash.analyzing': 'Scanning your audio files…',
  'splash.exploring': 'Exploring… {count} file|Exploring… {count} files',
  'splash.reading': 'Reading metadata {current}/{total}',
  'splash.ready': 'Ready',
  'splash.degraded': 'Starting in reduced mode',

  'scanner.exploring': 'Exploring folders…',
  'scanner.found': '{count} file found|{count} files found',
  'scanner.reading': 'Reading metadata…',
  'scanner.done': '{count} track in the library|{count} tracks in the library',

  'dialog.addFolder': 'Add a music folder'
}

export const messages: Record<Lang, Record<MessageKey, string>> = { fr, en }

export type Params = Record<string, string | number>

/** Anglais : seul 1 est singulier. Français : 0 et 1 le sont. */
const isPlural = (lang: Lang, count: number): boolean => (lang === 'en' ? count !== 1 : count > 1)

export function translate(lang: Lang, key: MessageKey, params?: Params): string {
  const table = messages[lang] ?? messages.fr
  let value: string = table[key] ?? messages.fr[key] ?? key

  if (value.includes('|')) {
    const [singular, plural] = value.split('|')
    const count = Number(params?.count ?? 0)
    value = isPlural(lang, count) ? plural : singular
  }

  if (!params) return value
  return value.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in params ? String(params[name]) : match
  )
}

/** Langue de départ déduite de la locale système, repli sur le français. */
export const detectLanguage = (locale: string | undefined): Lang =>
  locale?.toLowerCase().startsWith('en') ? 'en' : 'fr'
